#! /bin/sh
#
# This script assumes you have a simple HTTP server serving the WWW_LOCATION directory
#

SSH_URL="ubuntu@myipkg-feed.com"
WWW_LOCATION="/usr/share/nginx/html/"

find ./bin -type d -exec touch {}/index.html \;
ssh $SSH_URL mkdir -p /tmp/feed
scp -r bin/* $SSH_URL:/tmp/feed/
ssh $SSH_URL sudo rm -rf $WWW_LOCATION
ssh $SSH_URL sudo mkdir -p $WWW_LOCATION
ssh $SSH_URL sudo mv /tmp/feed/* $WWW_LOCATION
ssh $SSH_URL sudo chown -R www-data:www-data $WWW_LOCATION
